### ISSUE TITLE
Payment gateway

### ISSUE THREAD

**Issue by pooriaarab** [Lalit2005/pagely#174]
Hi, 

Great job with the repo. I was wondering how

-Can we add payment gateway (e.g. pay before accessing this notion doc/course)?
-Can we deploy to Hostinger?

**Comment by Lalit2005** [comment]
> -Can we add payment gateway (e.g. pay before accessing this notion doc/course)?

- You can use any tool like Gumroad to take payments and send the website created by Pagely. Additionally you can password protect it too!

**Comment by lalit2005** [comment]
Hey @pooriaarab 

- You can use any tool like Gumroad to take payments and send the website created by Pagely. Additionally you can password protect it too!

- The main goal of Pagely is to avoid all the hassle to setup deployment pipelines and hosting. And all the websites are hosted and heavily cached on the edge via Vercel's robust network. So there's no need of any external hosting services such as Hostinger
