### ISSUE TITLE
migration engine error s0 already exist

### ISSUE THREAD

**Issue by kelaspajak** [Lalit2005/pagely#40]
![image](https://user-images.githubusercontent.com/57969740/128520464-b97d33f2-f42d-4713-9212-98e7c017e008.png)

**Comment by Lalit2005** [comment]
Can you please be elaborate @kelaspajak

**Comment by pajakbalikpapan** [comment]
just restart supabase, thank u @Lalit2005

**Comment by kelaspajak** [comment]
just restart supabase, thank u @Lalit2005
